<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Validator;

class Language extends Model
{
    protected $fillable = ['name'];

    public function submissions()
    {
        return $this->hasMany('App\Models\Submission');
    }

    public function save(array $options = [])
    {
        $v = Validator::make($this->attributes, config('rules.language.store_validation_rules'));
        $v->validate();
        return parent::save($options); // TODO: Change the autogenerated stub
    }
}
